# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: To jest moja strona pokazowa.
email: krzysztofiak_84@o2.pl
description: > # this means to ignore newlines until "baseurl:"
  Tę stronę postawiłem dzięki internetowemu kursowi programowania na stronie codecademy.com, github.com oraz nazwa.pl. 
  Jest ona jeszcze w trakcie tworzenia, niemniej jestem zadowolony tak samo z niej jak i z siebie, w zwiąku z nabytymi umiejętnościami. 
  Gorąco zachęcam do nauki programowania!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Krzysztofiak
github_username:  Krzysztofiak

# Build settings
markdown: kramdown
